### ISSUE TITLE
SINTAXIS

### ISSUE THREAD

**Issue by Sandra631** [SistemasTecTlaxiaco/actividad-3-sintesis-Sandra631#2]
[Sintaxis_Gestión de Proyectos de Software.pdf](https://github.com/user-attachments/files/16832424/Sintaxis_Gestion.de.Proyectos.de.Software.pdf)

**Comment by Julissamigdalia** [comment]
bien hecho:
calificacion: 20

**Comment by josealfredo79** [comment]
La calificacion es de 18 faltan las referencias
